# Generated by Django 3.0 on 2024-02-02 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lettings", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Address",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "number",
                            models.PositiveIntegerField(
                                validators=[
                                    django.core.validators.MaxValueValidator(9999)
                                ]
                            ),
                        ),
                        ("street", models.CharField(max_length=64)),
                        ("city", models.CharField(max_length=64)),
                        (
                            "state",
                            models.CharField(
                                max_length=2,
                                validators=[
                                    django.core.validators.MinLengthValidator(2)
                                ],
                            ),
                        ),
                        (
                            "zip_code",
                            models.PositiveIntegerField(
                                validators=[
                                    django.core.validators.MaxValueValidator(99999)
                                ]
                            ),
                        ),
                        (
                            "country_iso_code",
                            models.CharField(
                                max_length=3,
                                validators=[
                                    django.core.validators.MinLengthValidator(3)
                                ],
                            ),
                        ),
                    ],
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="letting",
                    name="address",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lettings.Address",
                    ),
                ),
            ],
            # You're reusing an existing table, so do nothing
            database_operations=[],
        ),
    ]
